### 실습

In [1]:
import pandas as pd

1.RawData.xlsx를 불러오기
 ```python
 xls = pd.ExcelFile("RawData.xlsx")
 raw_df = xls.parse('Raw Aggregate',na_values=['NA'])
 ```
 
 
2. 의미없는 column 제거. "unnamed ~"
 ```python
 dataframe.drop(columns=열인덱싱 or 네이밍 등등)
 ```
 
 
3. 중복제거
 - 중복을 제거하는 함수: drop_duplicates(subset=['중복을 제거할 열'])
 - market, operator에는 merge가 포함된 열이 있음. 제거하기
 - https://yganalyst.github.io/data_handling/memo_9/



4. missing data를 median으로 대체하기
 - 참고: imputer는 문자형 변수가 있으면 안 돌아감.

In [10]:
#1 데이터 파일 불러오기
xls = pd.ExcelFile("D:/숙탯 2기/4주차_데이터 전처리/RawData.xlsx")
raw_df = xls.parse('Raw Aggregate',na_values=['NA'])

In [5]:
raw_df

,"Market, Operator",Q1 2000,Q2 2000,Q3 2000,Q4 2000,Q1 2001,Q2 2001,Q3 2001,Q4 2001,Q1 2002,...,Q3 2013,Q4 2013,Q1 2014,Q2 2014,Q3 2014,Q4 2014,Q1 2015,Q2 2015,Q3 2015,Q4 2015
0,Optus (Singtel),3.762613e+08,3.875217e+08,3.879526e+08,4.201218e+08,4.646951e+08,4.073518e+08,4.138521e+08,4.745215e+08,4.615209e+08,...,9.699885e+08,1.013061e+09,9.362292e+08,9.557495e+08,1.006101e+09,1.107939e+09,1.081938e+09,1.107217e+09,1.115162e+09,1.172220e+09
1,Telstra,5.404273e+08,5.404273e+08,5.611921e+08,5.611921e+08,5.781651e+08,5.781651e+08,6.052497e+08,6.579743e+08,6.038052e+08,...,1.755441e+09,1.755441e+09,1.735940e+09,1.735940e+09,1.923726e+09,1.923726e+09,1.922643e+09,1.922643e+09,1.995591e+09,1.995591e+09
2,Vodafone (Vodafone Hutchison),7.056431e+07,7.056431e+07,7.558399e+07,7.558399e+07,7.673959e+07,7.673959e+07,7.442838e+07,7.442838e+07,4.125809e+07,...,6.529907e+08,6.529907e+08,6.231616e+08,6.231616e+08,6.390512e+08,6.390512e+08,6.409291e+08,6.409291e+08,6.777641e+08,6.777641e+08
3,Vodafone (Merged Q2 2009),2.308060e+08,2.397659e+08,2.429228e+08,2.656079e+08,2.334697e+08,2.232040e+08,2.080456e+08,2.020614e+08,2.107543e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A1 Telekom (Telekom Austria),3.629594e+08,3.629594e+08,3.920844e+08,3.792870e+08,4.085224e+08,3.787354e+08,4.049921e+08,3.982624e+08,4.181085e+08,...,3.535244e+08,3.585230e+08,3.163726e+08,3.297373e+08,3.357172e+08,3.529157e+08,3.134248e+08,3.233434e+08,3.358279e+08,3.495234e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,GCI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.397900e+07,6.957700e+07,7.075300e+07,7.654600e+07,8.522100e+07,7.120400e+07,7.740800e+07,9.089200e+07,1.019110e+08,8.136100e+07
215,CLEAR (Clearwire) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,Alltel Wireless (ATN) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Vietnamobile (CK Hutchison / Hanoi Telecom),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.019908e+07,3.310748e+07,2.948697e+07,2.863828e+07,2.786081e+07,2.743812e+07,2.507572e+07,2.361516e+07,2.208803e+07,2.156283e+07
218,Gmobile (GTEL Mobile),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249958e+07,1.256441e+07,1.256305e+07,1.212328e+07,1.171719e+07,1.146272e+07,1.044042e+07,9.832306e+06,9.196481e+06,8.977811e+06

In [6]:
#2 의미없는 column 제거


#의미있는 column은 65개
raw_df.filter(regex = 'Q')    # Market~ 열 + Q~ 열 = 65개

,Q1 2000,Q2 2000,Q3 2000,Q4 2000,Q1 2001,Q2 2001,Q3 2001,Q4 2001,Q1 2002,Q2 2002,...,Q3 2013,Q4 2013,Q1 2014,Q2 2014,Q3 2014,Q4 2014,Q1 2015,Q2 2015,Q3 2015,Q4 2015
0,3.762613e+08,3.875217e+08,3.879526e+08,4.201218e+08,4.646951e+08,4.073518e+08,4.138521e+08,4.745215e+08,4.615209e+08,4.701880e+08,...,9.699885e+08,1.013061e+09,9.362292e+08,9.557495e+08,1.006101e+09,1.107939e+09,1.081938e+09,1.107217e+09,1.115162e+09,1.172220e+09
1,5.404273e+08,5.404273e+08,5.611921e+08,5.611921e+08,5.781651e+08,5.781651e+08,6.052497e+08,6.579743e+08,6.038052e+08,6.377512e+08,...,1.755441e+09,1.755441e+09,1.735940e+09,1.735940e+09,1.923726e+09,1.923726e+09,1.922643e+09,1.922643e+09,1.995591e+09,1.995591e+09
2,7.056431e+07,7.056431e+07,7.558399e+07,7.558399e+07,7.673959e+07,7.673959e+07,7.442838e+07,7.442838e+07,4.125809e+07,4.125809e+07,...,6.529907e+08,6.529907e+08,6.231616e+08,6.231616e+08,6.390512e+08,6.390512e+08,6.409291e+08,6.409291e+08,6.777641e+08,6.777641e+08
3,2.308060e+08,2.397659e+08,2.429228e+08,2.656079e+08,2.334697e+08,2.232040e+08,2.080456e+08,2.020614e+08,2.107543e+08,2.181234e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.629594e+08,3.629594e+08,3.920844e+08,3.792870e+08,4.085224e+08,3.787354e+08,4.049921e+08,3.982624e+08,4.181085e+08,4.035616e+08,...,3.535244e+08,3.585230e+08,3.163726e+08,3.297373e+08,3.357172e+08,3.529157e+08,3.134248e+08,3.233434e+08,3.358279e+08,3.495234e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.397900e+07,6.957700e+07,7.075300e+07,7.654600e+07,8.522100e+07,7.120400e+07,7.740800e+07,9.089200e+07,1.019110e+08,8.136100e+07
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.019908e+07,3.310748e+07,2.948697e+07,2.863828e+07,2.786081e+07,2.743812e+07,2.507572e+07,2.361516e+07,2.208803e+07,2.156283e+07
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249958e+07,1.256441e+07,1.256305e+07,1.212328e+07,1.171719e+07,1.146272e+07,1.044042e+07,9.832306e+06,9.196481e+06,8.977811e+06

In [7]:
raw_df = raw_df.drop(columns = raw_df.columns[66:])

In [8]:
raw_df

,"Market, Operator",Q1 2000,Q2 2000,Q3 2000,Q4 2000,Q1 2001,Q2 2001,Q3 2001,Q4 2001,Q1 2002,...,Q3 2013,Q4 2013,Q1 2014,Q2 2014,Q3 2014,Q4 2014,Q1 2015,Q2 2015,Q3 2015,Q4 2015
0,Optus (Singtel),3.762613e+08,3.875217e+08,3.879526e+08,4.201218e+08,4.646951e+08,4.073518e+08,4.138521e+08,4.745215e+08,4.615209e+08,...,9.699885e+08,1.013061e+09,9.362292e+08,9.557495e+08,1.006101e+09,1.107939e+09,1.081938e+09,1.107217e+09,1.115162e+09,1.172220e+09
1,Telstra,5.404273e+08,5.404273e+08,5.611921e+08,5.611921e+08,5.781651e+08,5.781651e+08,6.052497e+08,6.579743e+08,6.038052e+08,...,1.755441e+09,1.755441e+09,1.735940e+09,1.735940e+09,1.923726e+09,1.923726e+09,1.922643e+09,1.922643e+09,1.995591e+09,1.995591e+09
2,Vodafone (Vodafone Hutchison),7.056431e+07,7.056431e+07,7.558399e+07,7.558399e+07,7.673959e+07,7.673959e+07,7.442838e+07,7.442838e+07,4.125809e+07,...,6.529907e+08,6.529907e+08,6.231616e+08,6.231616e+08,6.390512e+08,6.390512e+08,6.409291e+08,6.409291e+08,6.777641e+08,6.777641e+08
3,Vodafone (Merged Q2 2009),2.308060e+08,2.397659e+08,2.429228e+08,2.656079e+08,2.334697e+08,2.232040e+08,2.080456e+08,2.020614e+08,2.107543e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A1 Telekom (Telekom Austria),3.629594e+08,3.629594e+08,3.920844e+08,3.792870e+08,4.085224e+08,3.787354e+08,4.049921e+08,3.982624e+08,4.181085e+08,...,3.535244e+08,3.585230e+08,3.163726e+08,3.297373e+08,3.357172e+08,3.529157e+08,3.134248e+08,3.233434e+08,3.358279e+08,3.495234e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,GCI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.397900e+07,6.957700e+07,7.075300e+07,7.654600e+07,8.522100e+07,7.120400e+07,7.740800e+07,9.089200e+07,1.019110e+08,8.136100e+07
215,CLEAR (Clearwire) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,Alltel Wireless (ATN) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Vietnamobile (CK Hutchison / Hanoi Telecom),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.019908e+07,3.310748e+07,2.948697e+07,2.863828e+07,2.786081e+07,2.743812e+07,2.507572e+07,2.361516e+07,2.208803e+07,2.156283e+07
218,Gmobile (GTEL Mobile),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249958e+07,1.256441e+07,1.256305e+07,1.212328e+07,1.171719e+07,1.146272e+07,1.044042e+07,9.832306e+06,9.196481e+06,8.977811e+06

In [9]:
#3 중복 제거

raw_df = raw_df.drop_duplicates(subset=raw_df[raw_df['Market, Operator'].str.contains("merge")])
raw_df

,"Market, Operator",Q1 2000,Q2 2000,Q3 2000,Q4 2000,Q1 2001,Q2 2001,Q3 2001,Q4 2001,Q1 2002,...,Q3 2013,Q4 2013,Q1 2014,Q2 2014,Q3 2014,Q4 2014,Q1 2015,Q2 2015,Q3 2015,Q4 2015
0,Optus (Singtel),3.762613e+08,3.875217e+08,3.879526e+08,4.201218e+08,4.646951e+08,4.073518e+08,4.138521e+08,4.745215e+08,4.615209e+08,...,9.699885e+08,1.013061e+09,9.362292e+08,9.557495e+08,1.006101e+09,1.107939e+09,1.081938e+09,1.107217e+09,1.115162e+09,1.172220e+09
1,Telstra,5.404273e+08,5.404273e+08,5.611921e+08,5.611921e+08,5.781651e+08,5.781651e+08,6.052497e+08,6.579743e+08,6.038052e+08,...,1.755441e+09,1.755441e+09,1.735940e+09,1.735940e+09,1.923726e+09,1.923726e+09,1.922643e+09,1.922643e+09,1.995591e+09,1.995591e+09
2,Vodafone (Vodafone Hutchison),7.056431e+07,7.056431e+07,7.558399e+07,7.558399e+07,7.673959e+07,7.673959e+07,7.442838e+07,7.442838e+07,4.125809e+07,...,6.529907e+08,6.529907e+08,6.231616e+08,6.231616e+08,6.390512e+08,6.390512e+08,6.409291e+08,6.409291e+08,6.777641e+08,6.777641e+08
3,Vodafone (Merged Q2 2009),2.308060e+08,2.397659e+08,2.429228e+08,2.656079e+08,2.334697e+08,2.232040e+08,2.080456e+08,2.020614e+08,2.107543e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A1 Telekom (Telekom Austria),3.629594e+08,3.629594e+08,3.920844e+08,3.792870e+08,4.085224e+08,3.787354e+08,4.049921e+08,3.982624e+08,4.181085e+08,...,3.535244e+08,3.585230e+08,3.163726e+08,3.297373e+08,3.357172e+08,3.529157e+08,3.134248e+08,3.233434e+08,3.358279e+08,3.495234e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,GCI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.397900e+07,6.957700e+07,7.075300e+07,7.654600e+07,8.522100e+07,7.120400e+07,7.740800e+07,9.089200e+07,1.019110e+08,8.136100e+07
215,CLEAR (Clearwire) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,Alltel Wireless (ATN) (Merged Q3 2013),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Vietnamobile (CK Hutchison / Hanoi Telecom),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.019908e+07,3.310748e+07,2.948697e+07,2.863828e+07,2.786081e+07,2.743812e+07,2.507572e+07,2.361516e+07,2.208803e+07,2.156283e+07
218,Gmobile (GTEL Mobile),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249958e+07,1.256441e+07,1.256305e+07,1.212328e+07,1.171719e+07,1.146272e+07,1.044042e+07,9.832306e+06,9.196481e+06,8.977811e+06

In [117]:
#4 결측값 중간값 대체


#결측치 확인
print(raw_df.isna().sum())

Market, Operator     0
Q1 2000             72
Q2 2000             72
Q3 2000             69
Q4 2000             69
                    ..
Q4 2014             43
Q1 2015             45
Q2 2015             46
Q3 2015             46
Q4 2015             46
Length: 65, dtype: int64

In [118]:
raw_df.info()     #1열만 object형

<class 'pandas.core.frame.DataFrame'>
Int64Index: 210 entries, 0 to 218
Data columns (total 65 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Market, Operator  210 non-null    object
 1   Q1 2000           138 non-null    float64
 2   Q2 2000           138 non-null    float64
 3   Q3 2000           141 non-null    float64
 4   Q4 2000           141 non-null    float64
 5   Q1 2001           146 non-null    float64
 6   Q2 2001           150 non-null    float64
 7   Q3 2001           150 non-null    float64
 8   Q4 2001           151 non-null    float64
 9   Q1 2002           153 non-null    float64
 10  Q2 2002           154 non-null    float64
 11  Q3 2002           154 non-null    float64
 12  Q4 2002           154 non-null    float64
 13  Q1 2003           158 non-null    float64
 14  Q2 2003           160 non-null    float64
 15  Q3 2003           160 non-null    float64
 16  Q4 2003           161 non-null    float64
 17  Q1 2004           160 non-null    float64
 18  Q2 2004           160 non-null    float64
 19  Q3 2004           160 non-null    float64
 20  Q4 2004           157 non-null    float64
 21  Q1 2005           161 non-null    float64
 22  Q2 2005           163 non-null    float64
 23  Q3 2005           163 non-null    float64
 24  Q4 2005           164 non-null    float64
 25  Q1 2006           164 non-null    float64
 26  Q2 2006           164 non-null    float64
 27  Q3 2006           163 non-null    float64
 28  Q4 2006           166 non-null    float64
 29  Q1 2007           173 non-null    float64
 30  Q2 2007           176 non-null    float64
 31  Q3 2007           176 non-null    float64
 32  Q4 2007           175 non-null    float64
 33  Q1 2008           176 non-null    float64
 34  Q2 2008           176 non-null    float64
 35  Q3 2008           180 non-null    float64
 36  Q4 2008           181 non-null    float64
 37  Q1 2009           180 non-null    float64
 38  Q2 2009           182 non-null    float64
 39  Q3 2009           185 non-null    float64
 40  Q4 2009           186 non-null    float64
 41  Q1 2010           187 non-null    float64
 42  Q2 2010           186 non-null    float64
 43  Q3 2010           187 non-null    float64
 44  Q4 2010           188 non-null    float64
 45  Q1 2011           187 non-null    float64
 46  Q2 2011           182 non-null    float64
 47  Q3 2011           182 non-null    float64
 48  Q4 2011           183 non-null    float64
 49  Q1 2012           183 non-null    float64
 50  Q2 2012           181 non-null    float64
 51  Q3 2012           181 non-null    float64
 52  Q4 2012           181 non-null    float64
 53  Q1 2013           180 non-null    float64
 54  Q2 2013           179 non-null    float64
 55  Q3 2013           177 non-null    float64
 56  Q4 2013           176 non-null    float64
 57  Q1 2014           173 non-null    float64
 58  Q2 2014           171 non-null    float64
 59  Q3 2014           169 non-null    float64
 60  Q4 2014           167 non-null    float64
 61  Q1 2015           165 non-null    float64
 62  Q2 2015           164 non-null    float64
 63  Q3 2015           164 non-null    float64
 64  Q4 2015           164 non-null    float64
dtypes: float64(64), object(1)
memory usage: 108.3+ KB

In [133]:
from numpy import nan
from sklearn.impute import SimpleImputer
values = raw_df.iloc[:, 1:].values       #object형인 1열 빼고 실행
imputer = SimpleImputer(missing_values = nan, strategy='median')
medianimputed = pd.DataFrame(imputer.fit_transform(values))
medianimputed

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,3.762613e+08,3.875217e+08,3.879526e+08,4.201218e+08,4.646951e+08,4.073518e+08,4.138521e+08,4.745215e+08,4.615209e+08,4.701880e+08,...,9.699885e+08,1.013061e+09,9.362292e+08,9.557495e+08,1.006101e+09,1.107939e+09,1.081938e+09,1.107217e+09,1.115162e+09,1.172220e+09
1,5.404273e+08,5.404273e+08,5.611921e+08,5.611921e+08,5.781651e+08,5.781651e+08,6.052497e+08,6.579743e+08,6.038052e+08,6.377512e+08,...,1.755441e+09,1.755441e+09,1.735940e+09,1.735940e+09,1.923726e+09,1.923726e+09,1.922643e+09,1.922643e+09,1.995591e+09,1.995591e+09
2,7.056431e+07,7.056431e+07,7.558399e+07,7.558399e+07,7.673959e+07,7.673959e+07,7.442838e+07,7.442838e+07,4.125809e+07,4.125809e+07,...,6.529907e+08,6.529907e+08,6.231616e+08,6.231616e+08,6.390512e+08,6.390512e+08,6.409291e+08,6.409291e+08,6.777641e+08,6.777641e+08
3,2.308060e+08,2.397659e+08,2.429228e+08,2.656079e+08,2.334697e+08,2.232040e+08,2.080456e+08,2.020614e+08,2.107543e+08,2.181234e+08,...,2.658760e+08,2.698939e+08,2.537406e+08,2.630151e+08,2.976488e+08,3.054183e+08,3.109898e+08,3.063000e+08,3.109415e+08,3.190766e+08
4,3.629594e+08,3.629594e+08,3.920844e+08,3.792870e+08,4.085224e+08,3.787354e+08,4.049921e+08,3.982624e+08,4.181085e+08,4.035616e+08,...,3.535244e+08,3.585230e+08,3.163726e+08,3.297373e+08,3.357172e+08,3.529157e+08,3.134248e+08,3.233434e+08,3.358279e+08,3.495234e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,7.946038e+07,8.595249e+07,9.423844e+07,1.016970e+08,9.247227e+07,1.050234e+08,1.097704e+08,1.063032e+08,1.021567e+08,1.092188e+08,...,7.397900e+07,6.957700e+07,7.075300e+07,7.654600e+07,8.522100e+07,7.120400e+07,7.740800e+07,9.089200e+07,1.019110e+08,8.136100e+07
206,7.946038e+07,8.595249e+07,9.423844e+07,1.016970e+08,9.247227e+07,1.050234e+08,1.097704e+08,1.063032e+08,1.021567e+08,1.092188e+08,...,2.658760e+08,2.698939e+08,2.537406e+08,2.630151e+08,2.976488e+08,3.054183e+08,3.109898e+08,3.063000e+08,3.109415e+08,3.190766e+08
207,7.946038e+07,8.595249e+07,9.423844e+07,1.016970e+08,9.247227e+07,1.050234e+08,1.097704e+08,1.063032e+08,1.021567e+08,1.092188e+08,...,2.658760e+08,2.698939e+08,2.537406e+08,2.630151e+08,2.976488e+08,3.054183e+08,3.109898e+08,3.063000e+08,3.109415e+08,3.190766e+08
208,7.946038e+07,8.595249e+07,9.423844e+07,1.016970e+08,9.247227e+07,1.050234e+08,1.097704e+08,1.063032e+08,1.021567e+08,1.092188e+08,...,4.019908e+07,3.310748e+07,2.948697e+07,2.863828e+07,2.786081e+07,2.743812e+07,2.507572e+07,2.361516e+07,2.208803e+07,2.156283e+07
209,7.946038e+07,8.595249e+07,9.423844e+07,1.016970e+08,9.247227e+07,1.050234e+08,1.097704e+08,1.063032e+08,1.021567e+08,1.092188e+08,...,1.249958e+07,1.256441e+07,1.256305e+07,1.212328e+07,1.171719e+07,1.146272e+07,1.044042e+07,9.832306e+06,9.196481e+06,8.977811e+06